const IndigenousWords = [
    "indigenous",
    "knowledge",
    "science",
    "soil",
    "land",
    "agriculture", 
    "nature",
    "intelligence",
    "ancestors",
    "health",
    "geology",
    "geography",
    "medicine",
    "astronomy",
    "philosophy",
    "economics",
    "song",
    "sun",
    "earth",
    "spirit",
    "water",
    "physics",
    "environment",
    "history",
    "food",
]

export default IndigenousWords;